#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SO8T Data Directory .gitkeep Creator
すべてのdata/サブディレクトリに.gitkeepファイルを作成してディレクトリ構造を保全

使用方法:
python scripts/utils/create_gitkeep_for_data_dirs.py
"""

import os
from pathlib import Path
from typing import List

def create_gitkeep_for_data_directories():
    """data/ディレクトリの全サブディレクトリに.gitkeepファイルを作成"""

    data_dir = Path("data")
    if not data_dir.exists():
        print("data/ directory not found")
        return

    created_count = 0
    skipped_count = 0

    # data/ディレクトリの全サブディレクトリを再帰的に探索
    for dir_path in sorted(data_dir.rglob("*")):
        if dir_path.is_dir():
            gitkeep_path = dir_path / ".gitkeep"

            # .gitkeepファイルが既に存在するか確認
            if gitkeep_path.exists():
                print(f"SKIP: {gitkeep_path} (already exists)")
                skipped_count += 1
                continue

            # 相対パスを計算
            relative_path = dir_path.relative_to(data_dir.parent)

            # .gitkeepファイルの内容を作成
            gitkeep_content = f"""# SO8T Data Directory Structure Keeper
# Directory: {relative_path}
# This file ensures the directory structure is maintained in Git
# Large dataset files are excluded via .gitignore for repository size management
# Dataset files are generated by scripts and stored in external locations when needed

# Directory created for: {dir_path.name}
# Parent structure preserved for dataset organization
"""

            # .gitkeepファイルを作成
            try:
                with open(gitkeep_path, 'w', encoding='utf-8') as f:
                    f.write(gitkeep_content)

                print(f"CREATE: {gitkeep_path}")
                created_count += 1

            except Exception as e:
                print(f"ERROR: Failed to create {gitkeep_path}: {e}")

    print("\n=== SUMMARY ===")
    print(f"Created .gitkeep files: {created_count}")
    print(f"Skipped existing files: {skipped_count}")
    print(f"Total directories processed: {created_count + skipped_count}")

    print("\n=== NEXT STEPS ===")
    print("1. Review .gitignore to ensure large data files are excluded")
    print("2. Run 'git add .' to stage directory structure")
    print("3. Run 'git commit -m \"feat: Preserve data directory structure with .gitkeep files\"'")
    print("4. Large dataset files will be excluded from Git while maintaining directory structure")

if __name__ == "__main__":
    print("SO8T Data Directory .gitkeep Creator")
    print("=" * 50)
    create_gitkeep_for_data_directories()
